// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0WTac2XQVQC92WscllKzVwvMU2Y9ieiI',
    appId: '1:121785143225:web:3587b661e4ce739b0df068',
    messagingSenderId: '121785143225',
    projectId: 'sentry-gas-home',
    authDomain: 'sentry-gas-home.firebaseapp.com',
    storageBucket: 'sentry-gas-home.firebasestorage.app',
    measurementId: 'G-QTEBMYCCFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXS7RK0ea-M4CGF-ayvTrxxCv9iyM6Exs',
    appId: '1:121785143225:android:4f443e7c940f11670df068',
    messagingSenderId: '121785143225',
    projectId: 'sentry-gas-home',
    storageBucket: 'sentry-gas-home.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzJbkohAIM_EpVnyjV41ZnV4k9pBOQG3A',
    appId: '1:121785143225:ios:c096f62868d71e3f0df068',
    messagingSenderId: '121785143225',
    projectId: 'sentry-gas-home',
    storageBucket: 'sentry-gas-home.firebasestorage.app',
    iosBundleId: 'com.example.sentryGasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzJbkohAIM_EpVnyjV41ZnV4k9pBOQG3A',
    appId: '1:121785143225:ios:c096f62868d71e3f0df068',
    messagingSenderId: '121785143225',
    projectId: 'sentry-gas-home',
    storageBucket: 'sentry-gas-home.firebasestorage.app',
    iosBundleId: 'com.example.sentryGasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0WTac2XQVQC92WscllKzVwvMU2Y9ieiI',
    appId: '1:121785143225:web:6dd916e8d08019710df068',
    messagingSenderId: '121785143225',
    projectId: 'sentry-gas-home',
    authDomain: 'sentry-gas-home.firebaseapp.com',
    storageBucket: 'sentry-gas-home.firebasestorage.app',
    measurementId: 'G-9KM3JY6VYQ',
  );
}
